[kubernetes]
format = 'on [ğŸ‹ $context \($namespace\)](white) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "white", symbol = "ğŸ’” " },
]

[username]
style_user = 'purple'
style_root = 'red'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false
